### ISSUE TITLE
Add Vagrant and Ansible

### ISSUE THREAD

**Issue by oakensoul** [web-masons/pyramid-zappa-api-boilerplate#8]
The project needs a standard Vagrantfile that uses a shell provisioner that calls out to the script/setup function, which will in turn use Ansible to bootstrap and then setup the box.

The bootstrap script should also be able to call out to Ansible to make sure that the dependencies are brought up to date.

**Comment by markdia** [comment]
nice

**Comment by oakensoul** [comment]
Currently I’m opting to only call bootstrap. Setup should be for application setup / configuration, which likely requires some developer input etc.
